# Generated by Django 5.2.4 on 2025-08-06 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(choices=[('Physician', 'Physician'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon')], max_length=100)),
                ('department', models.CharField(choices=[('General Medicine', 'General Medicine'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology'), ('Orthopedics', 'Orthopedics')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor')),
            ],
        ),
    ]
